          name,
          cityID,
          address,
          videoURL,
          ownerType,
          landmark,
          description,
          completionStatus,
          "completionDate": "2025-04-07T15:25:19.519Z",
          completionLevel,
          longitude,
          latitude,
          "features": [
            {
              "id": "string",
              "name": "string",
              "icon": "string",
              "hasAmpleParkingSpace": true,
              "hasUniformSecurity": true,
              "hasCCTVSurveillanceSystem": true,
              "hasInverter": true,
              "has24HoursElectricity": true,
              "hasInternetServices": true,
              "hasFiberOptics": true,
              "hasReliableWaterSupply": true,
              "hasChildernPlayground": true,
              "hasEquestrainOrPoloCenter": true,
              "hasTennisCourt": true,
              "hasGolfCourt": true,
              "hasLoungeOrBar": true,
              "hasResturant": true,
              "hasLakesOrPonds": true,
              "hasGazebos": true,
              "hasChildcareFacilities": true,
              "hasSchool": true,
              "hasHospital": true,
              "hasShoppingComplex": true,
              "hasChurchOrMosque": true,
              "hasGreeneryAndOpenGardens": true,
              "hasGym": true,
              "hasBasketballCourt": true,
              "hasFootballPitch": true,
              "hasSwimmingPool": true,
              "hasClubHouse": true,
              "hasBank": true,
              "hasCinema": true,
              "hasEnsuite": true,
              "hasPoPCeiling": true,
              "hasWalkInClosets": true,
              "hasAirConditioning": true,
              "hasSpeedInternet": true,
              "hasWineCeller": true,
              "hasFurnished": true,
              "hasWifi": true,
              "hasFibreOptics": true,
              "hasSatelliteTV": true,
              "hasElevator": true,
              "hasBoysQuarters": true,
              "hasSmartHomeTechnology": true,
              "hasFullyEquippedKitcken": true,
              "hasModernAppliances": true,
              "hasGraniteCountertops": true,
              "hasBreakfastBar": true,
              "hasStorageRoom": true,
              "hasUpgradedBathroomFeatures": true,
              "hasSpaLikeFeatures": true,
              "hasTileOrMarbleFeatures": true,
              "hasOpenFloorPlan": true,
              "hasLargeWindows": true,
              "hasBuiltInHouseTheater": true,
              "hasPrivateBackyard": true,
              "hasPatioOrDarkSpace": true,
              "hasLandscapedGarden": true,
              "hasHomeOfficeSpace": true,
              "hasBuiltInShelfOrBookSpace": true,
              "hasAmpleNaturalLight": true,
              "hasSecuritySystem": true,
              "hasBulletProofDoors": true,
              "hasGatedCompound": true,
              "hasReinforcedDoorsAndWindows": true,
              "hasGaurdedCommunity": true,
              "hasUniformedSecurity": true,
              "hasParkingGarage": true,
              "hasDriveWaySpace": true,
              "hasStreetParkingAvaliability": true,
              "hasPrivateParkingSpace": true,
              "hasElectricity": true,
              "hasBackupGenerator": true,
              "hasBorehole": true,
              "hasWaterBoard": true,
              "hasProximityToSchools": true,
              "hasProximityToShoppingMalls": true,
              "hasProximityToSupermarkets": true,
              "hasNearByPublicTransportation": true,
              "hasAccessiblityViaBoltOrUber": true,
              "hasFencedBackyard": true,
              "hasPetFriendlyNeighbourhood": true,
              "hasNearbyWalkingTrailsAndSidewalks": true
            }
          ],
          "feature": {
            "id": "string",
            "name": "string",
            "icon": "string",
            "hasAmpleParkingSpace": true,
            "hasUniformSecurity": true,
            "hasCCTVSurveillanceSystem": true,
            "hasInverter": true,
            "has24HoursElectricity": true,
            "hasInternetServices": true,
            "hasFiberOptics": true,
            "hasReliableWaterSupply": true,
            "hasChildernPlayground": true,
            "hasEquestrainOrPoloCenter": true,
            "hasTennisCourt": true,
            "hasGolfCourt": true,
            "hasLoungeOrBar": true,
            "hasResturant": true,
            "hasLakesOrPonds": true,
            "hasGazebos": true,
            "hasChildcareFacilities": true,
            "hasSchool": true,
            "hasHospital": true,
            "hasShoppingComplex": true,
            "hasChurchOrMosque": true,
            "hasGreeneryAndOpenGardens": true,
            "hasGym": true,
            "hasBasketballCourt": true,
            "hasFootballPitch": true,
            "hasSwimmingPool": true,
            "hasClubHouse": true,
            "hasBank": true,
            "hasCinema": true,
            "hasEnsuite": true,
            "hasPoPCeiling": true,
            "hasWalkInClosets": true,
            "hasAirConditioning": true,
            "hasSpeedInternet": true,
            "hasWineCeller": true,
            "hasFurnished": true,
            "hasWifi": true,
            "hasFibreOptics": true,
            "hasSatelliteTV": true,
            "hasElevator": true,
            "hasBoysQuarters": true,
            "hasSmartHomeTechnology": true,
            "hasFullyEquippedKitcken": true,
            "hasModernAppliances": true,
            "hasGraniteCountertops": true,
            "hasBreakfastBar": true,
            "hasStorageRoom": true,
            "hasUpgradedBathroomFeatures": true,
            "hasSpaLikeFeatures": true,
            "hasTileOrMarbleFeatures": true,
            "hasOpenFloorPlan": true,
            "hasLargeWindows": true,
            "hasBuiltInHouseTheater": true,
            "hasPrivateBackyard": true,
            "hasPatioOrDarkSpace": true,
            "hasLandscapedGarden": true,
            "hasHomeOfficeSpace": true,
            "hasBuiltInShelfOrBookSpace": true,
            "hasAmpleNaturalLight": true,
            "hasSecuritySystem": true,
            "hasBulletProofDoors": true,
            "hasGatedCompound": true,
            "hasReinforcedDoorsAndWindows": true,
            "hasGaurdedCommunity": true,
            "hasUniformedSecurity": true,
            "hasParkingGarage": true,
            "hasDriveWaySpace": true,
            "hasStreetParkingAvaliability": true,
            "hasPrivateParkingSpace": true,
            "hasElectricity": true,
            "hasBackupGenerator": true,
            "hasBorehole": true,
            "hasWaterBoard": true,
            "hasProximityToSchools": true,
            "hasProximityToShoppingMalls": true,
            "hasProximityToSupermarkets": true,
            "hasNearByPublicTransportation": true,
            "hasAccessiblityViaBoltOrUber": true,
            "hasFencedBackyard": true,
            "hasPetFriendlyNeighbourhood": true,
            "hasNearbyWalkingTrailsAndSidewalks": true
          },
          landSize,
          "images": [
            {
              "base64": "string",
              "ownerId": "string",
              "optionId": "string",
              "type": "string",
              "extension": "string",
              "description": "string",
              "document": image,
              "name": "string",
              "extraProperties": {
                "isCoverImage": true
              },
              "revisionId": "string"
            }
          ],
          organizerID,
          sellerID,
          floors